apiVersion: v1
kind: Job
metadata:
  name: pi

spec:
  completions: 8
  parallelism: 4
  backoffLimit: 4
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: pi
          image: perl
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
